# Generated by Django 2.1.15 on 2020-05-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0014_auto_20200524_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='other_component',
            field=models.TextField(null=True, verbose_name='Thành phần khác'),
        ),
    ]
