# Generated by Django 2.1.15 on 2020-06-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0019_merge_20200605_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='check_calender_letter',
            field=models.BooleanField(default=False, verbose_name='Trạng thái duyệt văn thư'),
        ),
    ]
