# Generated by Django 2.1.15 on 2020-06-19 10:55

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0020_calender_check_calender_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joincomponent',
            options={'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterModelOptions(
            name='prepareunit',
            options={'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ', 'verbose_name_plural': 'Hồ sơ'},
        ),
        migrations.AddField(
            model_name='calender',
            name='requirements',
            field=multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Hội nghị truyền hình'), (2, 'Màn hình trình chiếu'), (3, 'Backdrop'), (4, 'Tea-break'), (5, 'Đăng tài liệu cho khách ngoài CPC')], default=False, max_length=9, verbose_name='Yêu cầu'),
        ),
        migrations.AlterField(
            model_name='joincomponent',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='prepareunit',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Phòng ban'),
        ),
    ]
