# Generated by Django 2.1.15 on 2020-06-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0021_auto_20200619_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calender',
            name='join_component',
        ),
        migrations.RemoveField(
            model_name='calender',
            name='prepare_unit',
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement1',
            field=models.BooleanField(default=False, verbose_name='Hội nghị truyền hình'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement2',
            field=models.BooleanField(default=False, verbose_name='Màn hình trình chiếu'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement3',
            field=models.BooleanField(default=False, verbose_name='Backdrop'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement4',
            field=models.BooleanField(default=False, verbose_name='Tea-break'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement5',
            field=models.BooleanField(default=False, verbose_name='Đăng tài liệu cho khách ngoài CPC'),
        ),
        migrations.DeleteModel(
            name='JoinComponent',
        ),
        migrations.DeleteModel(
            name='PrepareUnit',
        ),
    ]
