# Generated by Django 2.1.15 on 2020-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0022_auto_20200619_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(blank=True, db_table='calender_jointcomponent', help_text='Nhấn giữ phím "Control", hoặc "Command" trên Mac, để chọn nhiều hơn một.', related_name='_calender_join_component_+', related_query_name='calender', to='calender.Department', verbose_name='Thành phần tham gia'),
        ),
        migrations.AddField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(blank=True, db_table='calender_prepareunit', help_text='Nhấn giữ phím "Control", hoặc "Command" trên Mac, để chọn nhiều hơn một.', related_name='_calender_prepare_unit_+', related_query_name='calender', to='calender.Department', verbose_name='Đơn vị chuẩn bị'),
        ),
    ]
