# Generated by Django 2.1.15 on 2020-06-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0023_auto_20200619_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(blank=True, db_table='calender_joincomponent', help_text='Nhấn giữ phím "Control", hoặc "Command" trên Mac, để chọn nhiều hơn một.', related_name='_calender_join_component_+', related_query_name='calender', to='calender.Department', verbose_name='Thành phần tham gia'),
        ),
    ]
