# Generated by Django 2.1.15 on 2020-06-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0024_auto_20200619_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='other_requirements',
            field=models.CharField(max_length=255, null=True, verbose_name='Yêu cầu khác'),
        ),
    ]
