# Generated by Django 2.1.15 on 2020-07-01 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calender', '0027_auto_20200622_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='Tuần')),
                ('content', models.TextField(help_text='Nội dung dự kiến tuần sau', verbose_name='Nội dung')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày sửa')),
                ('create_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa')),
            ],
        ),
        migrations.AlterField(
            model_name='calender',
            name='end_time',
            field=models.DateTimeField(help_text='Nếu ngày kết thúc > ngày bắt đầu thì phải ghi chú số ngày họp dưới phần nội dung, không tự động tạo nhiều lịch họp với số ngày', verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(db_table='calender_joincomponent', help_text='Nhấn giữ phím "Control", hoặc "Command" trên Mac, để chọn nhiều hơn một.', related_name='_calender_join_component_+', to='calender.Department', verbose_name='Thành phần tham gia'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='other_requirements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yêu cầu khác'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(db_table='calender_prepareunit', help_text='Nhấn giữ phím "Control", hoặc "Command" trên Mac, để chọn nhiều hơn một.', related_name='_calender_prepare_unit_+', to='calender.Department', verbose_name='Đơn vị chuẩn bị'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Phòng ban'),
        ),
    ]
