# Generated by Django 2.1.15 on 2020-07-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0028_auto_20200701_0936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expectedcalender',
            options={'verbose_name': 'Lịch dự kiến', 'verbose_name_plural': 'Lịch dự kiến'},
        ),
        # migrations.AddField(
        #     model_name='calender',
        #     name='other_prepare',
        #     field=models.TextField(blank=True, null=True, verbose_name='Đơn vị chuẩn bị khác'),
        # ),
        migrations.AlterField(
            model_name='calender',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm khác'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(db_table='calender_joincomponent', related_name='_calender_join_component_+', to='calender.Department', verbose_name='Thành phần tham gia'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Meeting', verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(db_table='calender_prepareunit', related_name='_calender_prepare_unit_+', to='calender.Department', verbose_name='Đơn vị chuẩn bị'),
        ),
    ]
