# Generated by Django 2.1.15 on 2020-07-15 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0031_auto_20200714_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='other_prepare',
            field=models.TextField(blank=True, null=True, verbose_name='Đơn vị chuẩn bị khác'),
        ),
        migrations.AddField(
            model_name='department',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
    ]
