# Generated by Django 2.1.15 on 2020-07-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0036_auto_20200716_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='create_depart_id',
            new_name='create_depart_id_id',
        ),
    ]
