# Generated by Django 2.1.15 on 2020-07-27 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0039_auto_20200723_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='cancel_status',
            field=models.IntegerField(choices=[(0, 'Bình thường'), (1, 'Hoãn/Huỷ'), (2, 'Thay đổi'), (3, 'Bổ sung'), (4, 'Đột xuất'), (5, 'Đổi địa điểm'), (6, 'Đổi thời gian')], default=0, verbose_name='Trạng thái lịch'),
        ),
    ]
