# Generated by Django 2.1.15 on 2020-08-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0040_auto_20200727_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Kích hoạt'),
        ),
    ]
