# Generated by Django 2.1.15 on 2021-04-29 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calender', '0048_remove_department_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255, verbose_name='Nội dung')),
                ('active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày sửa')),
                ('create_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa')),
            ],
            options={
                'verbose_name': 'Nội dung công việc',
                'verbose_name_plural': 'Nội dung công việc',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Trực thuộc phòng'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='chair_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Đơn vị đăng ký'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='content',
            field=models.TextField(blank=True, help_text='Nội dung cuộc họp', null=True, verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='other_component',
            field=models.TextField(blank=True, null=True, verbose_name='Thành phần'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='other_prepare',
            field=models.TextField(blank=True, null=True, verbose_name='Chuẩn bị'),
        ),
        migrations.AddField(
            model_name='calender',
            name='content_ids',
            field=models.ManyToManyField(blank=True, db_table='calender_content', related_name='_calender_content_ids_+', to='calender.CalendarContent', verbose_name='Nội dung công việc'),
        ),
    ]
