# Generated by Django 2.1.15 on 2020-11-14 10:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # ('calender', '0029_auto_20201114_1019'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver_Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(null=True, verbose_name='Ngày sửa')),
            ],
            options={
                'verbose_name': 'Phân công người lái',
                'verbose_name_plural': 'Phân công người lái',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên xe')),
                ('number', models.CharField(max_length=255, unique=True, verbose_name='Số xe')),
                ('frame_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số khung')),
                ('machine_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Số máy')),
                ('fuel', models.CharField(max_length=255, verbose_name='Nhiên liệu')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(null=True, verbose_name='Ngày sửa')),
                ('create_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('manage_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Đơn vị quản lý')),
            ],
            options={
                'verbose_name': 'Xe',
                'verbose_name_plural': 'Xe',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Vehicle_Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Kích hoạt')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(null=True, verbose_name='Ngày sửa')),
            ],
            options={
                'verbose_name': 'Phân công xe',
                'verbose_name_plural': 'Phân công xe',
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VehicleCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='Tuần')),
                ('start_time', models.DateTimeField(null=True, verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(help_text='Nếu ngày kết thúc > ngày bắt đầu thì phải ghi chú số ngày họp dưới phần nội dung, không tự động tạo nhiều lịch họp với số ngày', null=True, verbose_name='Thời gian kết thúc')),
                ('content', models.TextField(help_text='Nội dung công việc', verbose_name='Nội dung công việc')),
                ('departure', models.CharField(max_length=255, verbose_name='Nơi đi')),
                ('destination', models.CharField(max_length=255, verbose_name='Nơi đến')),
                ('expected_km', models.IntegerField(blank=True, null=True, verbose_name='Số km dự kiến')),
                ('expected_crane_hour', models.IntegerField(blank=True, null=True, verbose_name='Số giờ cẩu dự kiến (Nâng, cẩu)')),
                ('seat_number', models.IntegerField(verbose_name='Số người')),
                ('status', models.CharField(choices=[('NEW', 'Đăng ký'), ('CONFIRM', 'Xác nhận'), ('APPROVAL', 'Đã duyệt'), ('ASSIGNED', 'Đã phân xe'), ('CANCEL', 'Hủy/Hoãn')], default='NEW', max_length=8, verbose_name='Trạng thái lịch')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(null=True, verbose_name='Ngày sửa')),
                ('create_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('register_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Đơn vị đăng ký')),
            ],
            options={
                'verbose_name': 'Lịch xe',
                'verbose_name_plural': 'Lịch xe',
                'permissions': (('view_vehicle', 'Xem lịch xe'), ('register_vehicle', 'Đăng ký'), ('confirm_vehicle', 'Xác nhận'), ('approval_vehicle', 'Duyệt'), ('assign_vehicle', 'Phân công'), ('manage_vehicle', 'Quản lý')),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên loại xe')),
                ('is_left_tab', models.BooleanField(default=False, verbose_name='Tab hiển thị bên trái')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(null=True, verbose_name='Ngày sửa')),
                ('create_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa')),
            ],
            options={
                'verbose_name': 'Loại xe',
                'verbose_name_plural': 'Loại xe',
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='vehiclecalender',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleType', verbose_name='Tên loại xe'),
        ),
        migrations.AddField(
            model_name='vehiclecalender',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AddField(
            model_name='vehicle_division',
            name='calender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCalender', verbose_name='Lịch'),
        ),
        migrations.AddField(
            model_name='vehicle_division',
            name='create_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='vehicle_division',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Vehicle', verbose_name='Xe'),
        ),
        migrations.AddField(
            model_name='vehicle_division',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleType', verbose_name='Loại xe'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
        migrations.AddField(
            model_name='driver_division',
            name='calender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.VehicleCalender', verbose_name='Lịch'),
        ),
        migrations.AddField(
            model_name='driver_division',
            name='create_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AddField(
            model_name='driver_division',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người lái'),
        ),
        migrations.AddField(
            model_name='driver_division',
            name='write_uid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa'),
        ),
    ]
