# Generated by Django 2.1.15 on 2021-02-20 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecalender',
            name='is_appr_manager',
            field=models.BooleanField(default=False, verbose_name='Lãnh đạo duyệt'),
        ),
    ]
