# Generated by Django 2.1.15 on 2020-11-07 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên xe'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Số xe'),
        ),
    ]
