# Generated by Django 2.1.15 on 2020-11-07 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_auto_20201107_1215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclecalender',
            options={'default_permissions': (), 'permissions': (('view_vehicle', 'Xem lịch xe'), ('register_vehicle', 'Đăng ký'), ('confirm_vehicle', 'Xác nhận'), ('approval_vehicle', 'Duyệt'), ('assign_vehicle', 'Phân công'), ('manage_vehicle', 'Quản lý')), 'verbose_name': 'Lịch xe', 'verbose_name_plural': 'Lịch xe'},
        ),
    ]
