# Generated by Django 2.1.15 on 2020-11-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0003_auto_20201107_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='frame_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số khung'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='machine_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Số máy'),
        ),
    ]
