# Generated by Django 2.1.15 on 2020-12-25 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0048_remove_department_parent_id'),
        ('vehicle', '0004_auto_20201107_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecalender',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calender.Calender', verbose_name='Lịch tuần'),
        ),
    ]
