# Generated by Django 2.1.15 on 2020-12-25 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0005_vehiclecalender_calendar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclecalender',
            old_name='calendar',
            new_name='calender',
        ),
    ]
