# Generated by Django 2.1.15 on 2021-02-04 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vehicle', '0006_auto_20201225_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclecalender',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt'),
        ),
        migrations.AddField(
            model_name='vehiclecalender',
            name='is_appr_manager',
            field=models.BooleanField(default=False, verbose_name='Quản lý duyệt'),
        ),
    ]
