# Generated by Django 2.1.15 on 2020-05-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0016_auto_20200526_0829'),
        ('calender', '0016_auto_20200528_1439'),
    ]

    operations = [
    ]
