# Generated by Django 2.1.15 on 2020-06-05 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0018_auto_20200529_2157'),
        ('calender', '0017_merge_20200529_2205'),
    ]

    operations = [
    ]
