# Generated by Django 2.1.15 on 2020-06-22 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0026_remove_calender_requirements'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên phòng họp')),
                ('group', models.CharField(choices=[('IN', 'Trong cơ quan'), ('OUT', 'Ngoài cơ quan')], default='IN', max_length=3, verbose_name='Đơn vị')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Phòng họp',
                'verbose_name_plural': 'Phòng họp',
            },
        ),
        migrations.CreateModel(
            name='MultipleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Đính kèm tệp')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Calender', verbose_name='Lịch công tác')),
            ],
            options={
                'verbose_name': 'Đính kèm',
                'verbose_name_plural': 'Đính kèm',
            },
        ),
        migrations.AddField(
            model_name='calender',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Meeting', verbose_name='Địa điểm'),
        ),
    ]
