# Generated by Django 2.1.15 on 2020-07-08 22:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0029_auto_20200704_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='multiplefile',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Ngày tạo'),
            preserve_default=False,
        ),
    ]
