# Generated by Django 2.1.15 on 2020-07-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0030_auto_20200708_2241'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='calender',
        #     name='other_prepare',
        #     field=models.TextField(blank=True, null=True, verbose_name='Đơn vị chuẩn bị khác'),
        # ),
        migrations.AlterField(
            model_name='calender',
            name='cancel_status',
            field=models.IntegerField(choices=[(0, 'Bình thường'), (1, 'Hoãn/Huỷ'), (2, 'Thay đổi'), (3, 'Bổ sung'), (4, 'Đột xuất')], default=0, verbose_name='Trạng thái lịch'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(blank=True, db_table='calender_joincomponent', related_name='_calender_join_component_+', to='calender.Department', verbose_name='Thành phần tham gia'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(blank=True, db_table='calender_prepareunit', related_name='_calender_prepare_unit_+', to='calender.Department', verbose_name='Đơn vị chuẩn bị'),
        ),
    ]
