# Generated by Django 2.1.15 on 2020-07-16 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0032_auto_20200715_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='create_depart_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='calender.Department', verbose_name='Phòng tạo'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='chair_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Chủ trì'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='other_prepare',
            field=models.TextField(blank=True, null=True, verbose_name='Chuẩn bị khác'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(blank=True, db_table='calender_prepareunit', related_name='_calender_prepare_unit_+', to='calender.Department', verbose_name='Chuẩn bị'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='requirement5',
            field=models.BooleanField(default=False, verbose_name='Gửi tài liệu cho khách ngoài PC'),
        ),
    ]
