# Generated by Django 2.1.15 on 2020-10-20 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0044_auto_20201018_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_vehicle_calender',
            field=models.BooleanField(default=False, verbose_name='Lịch xe'),
        ),
    ]
