# Generated by Django 2.1.15 on 2021-02-04 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0048_remove_department_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Lãnh đạo'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm'),
        ),
    ]
