# Generated by Django 2.1.15 on 2020-05-14 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calender', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='Tuần')),
                ('start_time', models.DateTimeField(verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(verbose_name='Thời gian kết thúc')),
                ('address', models.CharField(max_length=255, verbose_name='Địa điểm')),
                ('join_quantity', models.IntegerField(verbose_name='Số lượng tham gia')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('attach_file', models.BinaryField(verbose_name='Đính kèm tệp')),
                ('status', models.CharField(choices=[('NEW', 'Chưa duyệt'), ('ACCEPT', 'Đã duyệt'), ('DONE', 'Hoàn thành')], default='NEW', max_length=6, verbose_name='Trạng thái')),
                ('cancel_status', models.BooleanField(verbose_name='Trạng thái hoãn')),
                ('note', models.TextField(verbose_name='Ghi chú')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(auto_now=True, verbose_name='Ngày sửa')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên phòng ban')),
                ('group', models.CharField(choices=[('IN', 'Trong cơ quan'), ('OUT', 'Ngoài cơ quan')], default='IN', max_length=3, verbose_name='Đơn vị')),
                ('note', models.TextField(verbose_name='Ghi chú')),
            ],
        ),
        migrations.CreateModel(
            name='JoinComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Calender')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PrepareUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Calender')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='date_of_birth',
            field=models.DateField(verbose_name='Ngày sinh'),
        ),
        migrations.AddField(
            model_name='calender',
            name='chair_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department'),
        ),
        migrations.AddField(
            model_name='calender',
            name='create_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(related_name='_calender_join_component_+', through='calender.JoinComponent', to='calender.Department'),
        ),
        migrations.AddField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(related_name='_calender_prepare_unit_+', through='calender.PrepareUnit', to='calender.Department'),
        ),
        migrations.AddField(
            model_name='person',
            name='department_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Department'),
        ),
    ]
