# Generated by Django 2.1.15 on 2020-05-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0003_auto_20200514_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='attach_file',
            field=models.FileField(upload_to='', verbose_name='Đính kèm tệp'),
        ),
    ]
