# Generated by Django 2.1.15 on 2020-05-16 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0006_auto_20200516_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(related_name='_calender_join_component_+', through='calender.JoinComponent', to='calender.Department', verbose_name='Thành phần tham gia'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(related_name='_calender_prepare_unit_+', through='calender.PrepareUnit', to='calender.Department', verbose_name='Đơn vị chuẩn bị'),
        ),
    ]
