# Generated by Django 2.1.15 on 2020-05-16 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0007_auto_20200516_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='depart',
            new_name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Department'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='chair_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Đơn vị chủ trì'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='content',
            field=models.TextField(help_text='Nội dung cuộc họp', verbose_name='Nội dung'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='create_uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
    ]
