# Generated by Django 2.1.15 on 2020-05-19 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('calender', '0008_auto_20200516_2107'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
        migrations.RemoveField(
            model_name='person',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='person',
            name='user_ptr',
        ),
        migrations.AlterModelOptions(
            name='calender',
            options={'verbose_name': 'Lịch công tác', 'verbose_name_plural': 'Lịch công tác'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Phòng ban', 'verbose_name_plural': 'Phòng ban'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Phòng ban'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng'),
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
