# Generated by Django 2.1.15 on 2020-05-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0009_auto_20200520_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='attach_file',
            field=models.FileField(null=True, upload_to='', verbose_name='Đính kèm tệp'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
    ]
