# Generated by Django 2.1.15 on 2020-05-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0010_auto_20200520_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='attach_file',
            field=models.FileField(null=True, upload_to='files', verbose_name='Đính kèm tệp'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='cancel_status',
            field=models.IntegerField(choices=[('0', 'Bình thường'), ('1', 'Hoãn/Huỷ'), ('2', 'Đổi thành phần'), ('3', 'Đổi thời gian'), ('4', 'Bổ sung')], default='0', max_length=6, verbose_name='Trạng thái lịch'),
        ),
    ]
