# Generated by Django 2.1.15 on 2020-05-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0012_remove_calender_cancel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='cancel_status',
            field=models.IntegerField(choices=[('0', 'Bình thường'), ('1', 'Hoãn/Huỷ'), ('2', 'Đổi thành phần'), ('3', 'Đổi thời gian'), ('4', 'Bổ sung')], default='0', verbose_name='Trạng thái lịch'),
        ),
    ]
