# Generated by Django 2.1.15 on 2020-05-24 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0013_calender_cancel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='note',
            field=models.TextField(null=True, verbose_name='Ghi chú'),
        ),
    ]
