# Generated by Django 2.1.15 on 2020-05-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0015_auto_20200526_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calender',
            name='attach_file',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Đính kèm tệp'),
        ),
    ]
