# Generated by Django 2.1.15 on 2020-07-02 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calender', '0020_calender_check_calender_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedCalender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField(verbose_name='Tuần')),
                ('content', models.TextField(help_text='Nội dung dự kiến tuần sau', verbose_name='Nội dung')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('write_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Ngày sửa')),
                ('create_uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('write_uid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Người sửa')),
            ],
            options={
                'verbose_name': 'Lịch dự kiến',
                'verbose_name_plural': 'Lịch dự kiến',
            },
        ),
        
    ]
