# Generated by Django 2.1.15 on 2020-07-14 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0022_auto_20200706_1426'),
    ]

    operations = [
        
        migrations.AlterField(
            model_name='calender',
            name='cancel_status',
            field=models.IntegerField(choices=[(0, 'Bình thường'), (1, 'Hoãn/Huỷ'), (2, 'Thay đổi'), (3, 'Bổ sung'), (4, 'Đột xuất')], default=0, verbose_name='Trạng thái lịch'),
        ),
    ]
