# Generated by Django 2.1.15 on 2020-07-16 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0023_auto_20200714_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='sequence',
            field=models.IntegerField(default=0, verbose_name='Thứ tự'),
        ),
    ]
