# Generated by Django 2.1.15 on 2020-07-17 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0024_auto_20200716_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='create_depart_id_id',
            field=models.IntegerField(default=1, verbose_name='Phòng tạo'),
        ),
    ]
