# Generated by Django 2.1.15 on 2020-08-01 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0025_auto_20200717_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='slide_show',
            field=models.BooleanField(default=False, verbose_name='Trình chiếu'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='cancel_status',
            field=models.IntegerField(choices=[(0, 'Bình thường'), (1, 'Hoãn/Huỷ'), (2, 'Thay đổi'), (3, 'Bổ sung'), (4, 'Đột xuất'), (5, 'Đổi địa điểm'), (6, 'Đổi thời gian')], default=0, verbose_name='Trạng thái lịch'),
        ),
    ]
