# Generated by Django 2.1.15 on 2020-11-14 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0028_auto_20201024_1128'),
    ]

    operations = [
        
    ]
