# Generated by Django 2.1.15 on 2021-02-20 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0029_auto_20201114_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='Ban giám đốc'),
        )
    ]
