# Generated by Django 2.1.15 on 2021-02-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0030_auto_20210220_0841'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tên phòng họp')),
                ('group', models.CharField(choices=[('IN', 'Trong cơ quan'), ('OUT', 'Ngoài cơ quan')], default='IN', max_length=3, verbose_name='Đơn vị')),
                ('sequence', models.IntegerField(default=0, verbose_name='Thứ tự')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
            options={
                'verbose_name': 'Phòng họp',
                'verbose_name_plural': 'Phòng họp',
            },
        ),
        migrations.CreateModel(
            name='MultipleFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='', verbose_name='Đính kèm tệp')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
            ],
            options={
                'verbose_name': 'Đính kèm',
                'verbose_name_plural': 'Đính kèm',
            },
        ),
        migrations.RemoveField(
            model_name='joincomponent',
            name='calender',
        ),
        migrations.RemoveField(
            model_name='joincomponent',
            name='department',
        ),
        migrations.RemoveField(
            model_name='prepareunit',
            name='calender',
        ),
        migrations.RemoveField(
            model_name='prepareunit',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Hồ sơ', 'verbose_name_plural': 'Hồ sơ'},
        ),
        migrations.AddField(
            model_name='calender',
            name='other_requirements',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Yêu cầu khác'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement1',
            field=models.BooleanField(default=False, verbose_name='Hội nghị truyền hình'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement2',
            field=models.BooleanField(default=False, verbose_name='Màn hình trình chiếu'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement3',
            field=models.BooleanField(default=False, verbose_name='Backdrop'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement4',
            field=models.BooleanField(default=False, verbose_name='Tea-break'),
        ),
        migrations.AddField(
            model_name='calender',
            name='requirement5',
            field=models.BooleanField(default=False, verbose_name='Gửi tài liệu cho khách ngoài PC'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa điểm'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='chair_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Chủ trì'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='create_depart_id_id',
            field=models.IntegerField(verbose_name='Phòng tạo'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='end_time',
            field=models.DateTimeField(help_text='Nếu ngày kết thúc > ngày bắt đầu thì phải ghi chú số ngày họp dưới phần nội dung, không tự động tạo nhiều lịch họp với số ngày', verbose_name='Thời gian kết thúc'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='join_component',
            field=models.ManyToManyField(blank=True, db_table='calender_joincomponent', related_name='_calender_join_component_+', to='calender.Department', verbose_name='Thành phần tham gia'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='other_prepare',
            field=models.TextField(blank=True, null=True, verbose_name='Chuẩn bị khác'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='prepare_unit',
            field=models.ManyToManyField(blank=True, db_table='calender_prepareunit', related_name='_calender_prepare_unit_+', to='calender.Department', verbose_name='Chuẩn bị'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Department', verbose_name='Phòng ban'),
        ),
        migrations.DeleteModel(
            name='JoinComponent',
        ),
        migrations.DeleteModel(
            name='PrepareUnit',
        ),
        migrations.AddField(
            model_name='multiplefile',
            name='calendar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calender.Calender', verbose_name='Lịch công tác'),
        ),
        migrations.AddField(
            model_name='calender',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calender.Meeting', verbose_name='Địa điểm'),
        ),
    ]
