# Generated by Django 2.1.15 on 2020-07-23 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0038_meeting_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='slide_show',
            field=models.BooleanField(default=False, verbose_name='Trình chiếu'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='cancel_status',
            field=models.IntegerField(choices=[(0, 'Bình thường'), (1, 'Hoãn/Huỷ'), (2, 'Thay đổi'), (3, 'Bổ sung'), (4, 'Đột xuất'), (5, 'Đổi địa điểm')], default=0, verbose_name='Trạng thái lịch'),
        ),
        migrations.AlterField(
            model_name='calender',
            name='create_depart_id_id',
            field=models.IntegerField(verbose_name='Phòng tạo'),
        ),
    ]
