# Generated by Django 2.1.15 on 2020-10-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0043_auto_20201015_2004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='working_division',
            options={'default_permissions': (), 'verbose_name': 'Phân công dự họp', 'verbose_name_plural': 'Phân công dự họp'},
        ),
    ]
