# Generated by Django 2.1.15 on 2020-10-20 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0045_department_is_vehicle_calender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_driver',
            field=models.BooleanField(default=False, verbose_name='Lái xe'),
        ),
    ]
