# Generated by Django 2.1.15 on 2020-11-29 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calender', '0047_department_parent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='parent_id',
        ),
    ]
